# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      #Setup nodejs 
      # - name: Setup Node.js environment
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      
      - name: Run Test
        run: npm test
  
  # Deploye
  deploy:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, ARM64]

    steps:
      # - name: Check out
      #   uses: actions/checkout@v2
      # - name: Remove 
      #   run: "rm -rf /usr/share/nodeproject/node-js-ci-cd-github-actions"
      # - name: Make 
      #   run: "mkdir /usr/share/nodeproject/node-js-ci-cd-github-actions"
      # - name: Move 
      #   run: "mv /var/www/html/actions-runner/_work/node-js-ci-cd-github-actions/node-js-ci-cd-github-actions/*  /usr/share/nodeproject/node-js-ci-cd-github-actions"
      # - name: Install 
      #   run: "cd /usr/share/nodeproject/node-js-ci-cd-github-actions && npm install && node src/"
      # - name: Install 
      #   run: "cd /usr/share/nodeproject/node-js-ci-cd-github-actions && npm install && node src/"
      
      - name: Check out To Project Directory
        run: "cd /usr/share/nodeproject"
      - name: Print PWD
        run: "echo pwd"
      - name: Remove 
        run: "rm -rf node-js-ci-cd-github-actions"
      - name: Check out
        uses: actions/checkout@v2
      - name: Print PWD
        run: "echo pwd"
        
 



                
